[project]
name = "backend"
version = "0.1.0"
description = "Server-Sent Events (SSE) with FastAPI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.8",
    "sse-starlette>=2.2.1",
    "uvicorn>=0.34.0",
]
